FROM openjdk
MAINTAINER Vinothkumar Selvaraj <vinothkumar1.selvaraj@gmail.com>
ADD target/customer-service.jar customer-service.jar
ENTRYPOINT ["java", "-jar", "/customer-service.jar"]
EXPOSE 3333
